# Generated by Django 6.1.1 on 2026-09-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todomanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
